PACKAGE_NAME="mt7603usta"
PACKAGE_VERSION="1.14"
CLEAN="make clean"
MAKE[0]="make KSRC=/lib/modules/${kernelver}/build DARK_MODE=NO -j$(nproc)"
BUILT_MODULE_NAME[0]="mt7603usta"
BUILT_MODULE_LOCATION[0]="os/linux/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless/"
AUTOINSTALL="yes"
